[info]
name="NXP"
version="v1.0.0"
codev="252518"

[repos]
def-repo="https://raw.githubusercontent.com/hithja/nxp-repo/main" #! Don't touch this

[path]
bin="~/.bin"
cache=".cache"
conf-folder="~/.config/nxp"
nxpi=".nxpi"
conf-file=".nxprc"
help-file="./help.txt"